/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superdeliverysystem;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import superdeliverysystem.SuperDeliverySystem;
import superdeliverysystem.connectionClass;

/**
 *
 * @author Sweera
 */
public class edit_prov1 extends javax.swing.JFrame {

    /**
     * Creates new form edit_prov
     */
    public edit_prov1() {
        initComponents();
        buttonGroup1.add(Large);
        buttonGroup1.add(small);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        UpdateVehicleInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        LN = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        Cpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        Plate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        small = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Make = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Large = new javax.swing.JRadioButton();
        ee = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lnum = new javax.swing.JTextField();
        UpdatePersonalInfo1 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setMinimumSize(new java.awt.Dimension(850, 850));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 600, 80, 25);

        UpdateVehicleInfo.setBackground(new java.awt.Color(255, 0, 0));
        UpdateVehicleInfo.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        UpdateVehicleInfo.setForeground(new java.awt.Color(255, 255, 255));
        UpdateVehicleInfo.setText("UpdateVehicleInfo");
        UpdateVehicleInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVehicleInfoActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateVehicleInfo);
        UpdateVehicleInfo.setBounds(510, 550, 230, 25);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.darkGray);
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 340, 120, 30);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.darkGray);
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 390, 130, 20);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.darkGray);
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 430, 120, 20);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.darkGray);
        jLabel4.setText("Confirm Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 470, 170, 20);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.darkGray);
        jLabel5.setText("Phone Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 510, 150, 20);

        FN.setMaximumSize(new java.awt.Dimension(7, 21));
        FN.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(FN);
        FN.setBounds(200, 340, 140, 30);

        LN.setMaximumSize(new java.awt.Dimension(7, 21));
        LN.setMinimumSize(new java.awt.Dimension(7, 21));
        LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNActionPerformed(evt);
            }
        });
        jPanel1.add(LN);
        LN.setBounds(200, 380, 140, 30);

        phone.setMaximumSize(new java.awt.Dimension(7, 21));
        phone.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(phone);
        phone.setBounds(200, 500, 140, 30);

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Personal Information");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 240, 220, 20);

        Pass.setMaximumSize(new java.awt.Dimension(7, 21));
        Pass.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(Pass);
        Pass.setBounds(200, 420, 140, 30);

        Cpass.setMaximumSize(new java.awt.Dimension(7, 21));
        Cpass.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(Cpass);
        Cpass.setBounds(200, 460, 140, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Vehicle Information");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 240, 210, 20);

        Plate.setMaximumSize(new java.awt.Dimension(7, 21));
        Plate.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(Plate);
        Plate.setBounds(610, 360, 140, 30);

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.darkGray);
        jLabel9.setText("Plate Number");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 370, 150, 20);

        small.setBackground(new java.awt.Color(153, 255, 255));
        small.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        small.setText("Small");
        small.setOpaque(false);
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });
        jPanel1.add(small);
        small.setBounds(560, 470, 110, 30);

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.darkGray);
        jLabel10.setText("Make");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 420, 130, 20);

        Make.setMaximumSize(new java.awt.Dimension(7, 21));
        Make.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(Make);
        Make.setBounds(610, 410, 140, 30);

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.darkGray);
        jLabel11.setText("Car Size");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 470, 110, 20);

        Large.setBackground(new java.awt.Color(153, 255, 255));
        Large.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        Large.setText("Large");
        Large.setOpaque(false);
        jPanel1.add(Large);
        Large.setBounds(640, 470, 110, 30);

        ee.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        ee.setForeground(java.awt.Color.darkGray);
        ee.setText("Email");
        jPanel1.add(ee);
        ee.setBounds(50, 310, 100, 20);

        email.setMaximumSize(new java.awt.Dimension(7, 21));
        email.setMinimumSize(new java.awt.Dimension(7, 21));
        jPanel1.add(email);
        email.setBounds(200, 300, 140, 30);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel12.setForeground(java.awt.Color.darkGray);
        jLabel12.setText("License Number");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(450, 320, 150, 20);

        lnum.setMaximumSize(new java.awt.Dimension(7, 21));
        lnum.setMinimumSize(new java.awt.Dimension(7, 21));
        lnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnumActionPerformed(evt);
            }
        });
        jPanel1.add(lnum);
        lnum.setBounds(610, 310, 140, 30);

        UpdatePersonalInfo1.setBackground(new java.awt.Color(255, 0, 0));
        UpdatePersonalInfo1.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        UpdatePersonalInfo1.setForeground(new java.awt.Color(255, 255, 255));
        UpdatePersonalInfo1.setText("Update Personal Info");
        UpdatePersonalInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePersonalInfo1ActionPerformed(evt);
            }
        });
        jPanel1.add(UpdatePersonalInfo1);
        UpdatePersonalInfo1.setBounds(100, 550, 230, 25);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Edit Account");
        jPanel1.add(label1);
        label1.setBounds(160, 50, 440, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        ProviderHomePage_2 ProviderHomePage_2 = new ProviderHomePage_2();
        ProviderHomePage_2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UpdateVehicleInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVehicleInfoActionPerformed

        String query2, size;
        int result2;

        if (small.isSelected()) {
            size = "Small";
        } else {
            size = "Large";
        }

        if (Plate.getText().equalsIgnoreCase("") || Make.getText().equalsIgnoreCase("") || !(small.isSelected() || Large.isSelected())) {
            JOptionPane.showMessageDialog(null, "Make sure you have filled all required fields.", "Entry Error", JOptionPane.ERROR_MESSAGE);

        } else {

            connectionClass.getConnection();
            query2 = "update vehicle set make = '" + Make.getText() + "', platenumber = '" + Plate.getText() + "', size = '" + size + "' where LicenseNumber = '" + lnum.getText() + "'";
            result2 = connectionClass.getResrultsetupdate(query2);

            if (result2 > 0 ) {
                JOptionPane.showMessageDialog(null, "Changed succesfully", "Success!", JOptionPane.OK_OPTION);
                setVisible(false);
                ProviderHomePage_2 ProviderHomePage_2 = new ProviderHomePage_2();
                ProviderHomePage_2.setVisible(true);
            }
        }

    }//GEN-LAST:event_UpdateVehicleInfoActionPerformed

    private void LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNActionPerformed

    }//GEN-LAST:event_LNActionPerformed

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed

    }//GEN-LAST:event_smallActionPerformed

    private void lnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnumActionPerformed

    private void UpdatePersonalInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePersonalInfo1ActionPerformed
        String query1;
        int result1;

        if (FN.getText().equalsIgnoreCase("") || LN.getText().equalsIgnoreCase("") || Pass.getText().equalsIgnoreCase("") || Cpass.getText().equalsIgnoreCase("") || phone.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Make sure you have filled all required fields.", "Entry Error", JOptionPane.ERROR_MESSAGE);

        } else if (!(Arrays.equals(Pass.getPassword(), Cpass.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Password fields do not match, please try again.", "OOPS", JOptionPane.ERROR_MESSAGE);
        } else {

            connectionClass.getConnection();

            query1 = "update account set firstname='" + FN.getText() + "',lastname='" + LN.getText() + "',password='" + Pass.getPassword().toString() + "', phonenumber= '" + phone.getText() + "' where email='" + email.getText() + "'";
            result1 = connectionClass.getResrultsetupdate(query1);

            if (result1 > 0) {
                JOptionPane.showMessageDialog(null, "Changed succesfully", "Success!", JOptionPane.OK_OPTION);
                setVisible(false);
                ProviderHomePage_2 ProviderHomePage_2 = new ProviderHomePage_2();
                ProviderHomePage_2.setVisible(true);
            }
        }
    }//GEN-LAST:event_UpdatePersonalInfo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_prov1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_prov1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_prov1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_prov1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_prov1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cpass;
    private javax.swing.JTextField FN;
    private javax.swing.JTextField LN;
    private javax.swing.JRadioButton Large;
    private javax.swing.JTextField Make;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JTextField Plate;
    private javax.swing.JButton UpdatePersonalInfo1;
    private javax.swing.JButton UpdateVehicleInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel ee;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JTextField lnum;
    private javax.swing.JTextField phone;
    private javax.swing.JRadioButton small;
    // End of variables declaration//GEN-END:variables
}
