/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superdeliverysystem;

//import az.Admin_ViewCarriedOutOrders_3;
//import az.Register_2;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aseer
 */
public class LoginPage_1 extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        loginPW = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        loginEMAIL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in");
        setMaximumSize(new java.awt.Dimension(850, 850));
        setMinimumSize(new java.awt.Dimension(850, 850));
        setPreferredSize(new java.awt.Dimension(850, 850));
        setSize(new java.awt.Dimension(850, 850));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 510, 170, 29);

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 510, 130, 29);

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setText("more info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 510, 101, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("New user? Create an account!");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 460, 190, 15);
        getContentPane().add(loginPW);
        loginPW.setBounds(520, 390, 140, 30);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 400, 90, 20);

        loginEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEMAILActionPerformed(evt);
            }
        });
        getContentPane().add(loginEMAIL);
        loginEMAIL.setBounds(520, 310, 140, 30);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Welcome again");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 200, 440, 50);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 320, 51, 20);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/superdeliverysystem/logo3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(538, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(161, 161, 161))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addContainerGap(639, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Go through records in sds.Accounts and check email/password
        String login_email = loginEMAIL.getText();
        String login_password = loginPW.getText();

        if (isAdmin(login_email, login_password)) {
            AdminHomePage_2 a = new AdminHomePage_2();
            a.setVisible(true);
        } else if (!isAccount(login_email, login_password)) {
            JOptionPane.showMessageDialog(null, "Either email or password doesn't match, please try again!");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean isAdmin(String login_email, String login_password) {

        boolean flag = false;

        try {
            Connection con = connectionClass.getConnection();
            String queryString = "SELECT email, password FROM admin";
            Statement s = con.createStatement();
            ResultSet results = s.executeQuery(queryString);

            while (results.next()) {
                String email = results.getString("email");
                String password = results.getString("password");

                if ((login_email.equals(email)) && (login_password.equals(password))) {
                    flag = true;
                    setVisible(false);
                    return flag;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }

    public boolean isAccount(String login_email, String login_password) {

        boolean flag = false;

        try {
            Connection con = connectionClass.getConnection();
            String queryString = "SELECT email, password, type FROM account";
            Statement s = con.createStatement();
            ResultSet results = s.executeQuery(queryString);

            while (results.next()) {
                String email = results.getString("email");
                String password = results.getString("password");
                String type = results.getString("type");

                if ((login_email.equals(email)) && (login_password.equals(password))) {
                    flag = true;
                    if ("benefiter".equals(type)) {
                        BenefiterHomePage_2 b = new BenefiterHomePage_2();
                        b.setVisible(true);
                    } else if ("provider".equals(type)) {
                        ProviderHomePage_2 p = new ProviderHomePage_2();
                        p.setVisible(true);
                    }
                    setVisible(false);
                    return flag;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        Register_2 register = new Register_2();
        register.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        aboutus aboutus = new aboutus();
        aboutus.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loginEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEMAILActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage_1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField loginEMAIL;
    private javax.swing.JPasswordField loginPW;
    // End of variables declaration//GEN-END:variables
}
