package superdeliverysystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aseer
 */
public class Register_2 extends javax.swing.JFrame {
     String type;
    private final String admin = "Admin Tameem";
    public static int accountCount ;
    ExceptionChecker ExceptionChecker = new ExceptionChecker();
    
    DoYouOwnAVehicle_3 popup = new DoYouOwnAVehicle_3();

    /**
     * Creates new form Register_2
     */
    public Register_2() {
        initComponents();
        //jPanel1.setBackground(new Color(0, 0, 0, 43));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rad_b = new javax.swing.JRadioButton();
        rad_p = new javax.swing.JRadioButton();
        district_txt = new javax.swing.JTextField();
        city = new javax.swing.JComboBox<>();
        phoneNumber_txt = new javax.swing.JTextField();
        pw_2 = new javax.swing.JPasswordField();
        pw_1 = new javax.swing.JPasswordField();
        email_txt = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        lname_txt = new javax.swing.JTextField();
        fname_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_txt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Clear All Fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 630, 840, 150);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        buttonGroup1.add(rad_b);
        rad_b.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        rad_b.setForeground(new java.awt.Color(0, 102, 0));
        rad_b.setText("Benefiter");
        rad_b.setToolTipText("Place orders to be carried-out by providers.");
        rad_b.setBorderPainted(true);
        rad_b.setOpaque(false);
        rad_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_bActionPerformed(evt);
            }
        });
        jPanel1.add(rad_b);
        rad_b.setBounds(630, 270, 90, 25);

        buttonGroup1.add(rad_p);
        rad_p.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        rad_p.setForeground(new java.awt.Color(51, 51, 51));
        rad_p.setText("Provider");
        rad_p.setToolTipText("Carry-out requests from benefiters complying prestated requirements");
        rad_p.setBorderPainted(true);
        rad_p.setOpaque(false);
        rad_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_pActionPerformed(evt);
            }
        });
        jPanel1.add(rad_p);
        rad_p.setBounds(510, 270, 90, 25);

        district_txt.setToolTipText("");
        district_txt.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(district_txt);
        district_txt.setBounds(550, 190, 140, 21);

        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Abha", "Abqaiq", "Al-Bahah", "Al-Dammam", "Al-Hufuf", "Al-Jawf", "Al-Kharj (oasis)", "Al-Khubar", "Al-Qatif", "Al-Taʾif", "ʿArʿar", "Buraydah", "Dhahran", "Haʾil", "Jeddah", "Jizan", "Khamis Mushayt", "King Khalid Military City", "Mecca", "Medina", "Najran", "Ras Tanura", "Riyadh", "Sakaka", "Tabuk", "Yanbu" }));
        jPanel1.add(city);
        city.setBounds(550, 150, 140, 20);

        phoneNumber_txt.setToolTipText("");
        phoneNumber_txt.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(phoneNumber_txt);
        phoneNumber_txt.setBounds(550, 110, 140, 21);

        pw_2.setToolTipText("");
        pw_2.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(pw_2);
        pw_2.setBounds(170, 310, 140, 21);

        pw_1.setToolTipText("");
        pw_1.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(pw_1);
        pw_1.setBounds(170, 270, 140, 21);

        email_txt.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(email_txt);
        email_txt.setBounds(170, 230, 140, 21);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        year.setToolTipText("year");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year);
        year.setBounds(250, 190, 60, 20);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.setToolTipText("month");
        jPanel1.add(month);
        month.setBounds(210, 190, 40, 20);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setToolTipText("day");
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        jPanel1.add(day);
        day.setBounds(170, 190, 40, 20);

        lname_txt.setToolTipText("");
        lname_txt.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(lname_txt);
        lname_txt.setBounds(170, 150, 140, 21);

        fname_txt.setToolTipText("");
        fname_txt.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(fname_txt);
        fname_txt.setBounds(170, 110, 140, 21);

        jLabel13.setBackground(new java.awt.Color(0, 204, 204));
        jLabel13.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Register as a:");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(400, 240, 110, 20);

        jLabel12.setBackground(new java.awt.Color(0, 204, 204));
        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("District");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 190, 120, 20);

        jLabel11.setBackground(new java.awt.Color(0, 204, 204));
        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("City");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 150, 80, 20);

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Phone Number");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 110, 140, 20);

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Confirm Password");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 310, 142, 20);

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Password");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 270, 100, 20);

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Email");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 230, 80, 20);

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Date of Birth");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 190, 130, 20);

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Last Name");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 150, 100, 20);

        name_txt.setBackground(new java.awt.Color(0, 204, 204));
        name_txt.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        name_txt.setForeground(new java.awt.Color(51, 51, 51));
        name_txt.setText("First Name");
        name_txt.setOpaque(true);
        jPanel1.add(name_txt);
        name_txt.setBounds(30, 110, 100, 20);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(10, 210, 830, 360);

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Enter your information below:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 170, 430, 33);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 850, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void rad_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_pActionPerformed
        if (rad_p.isSelected()) {
                 type="provider";
            popup.setVisible(true);
        }
    }//GEN-LAST:event_rad_pActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        LoginPage_1 LoginPage_1 = new LoginPage_1();
        LoginPage_1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fname_txt.setText("");
        lname_txt.setText("");
        email_txt.setText("");
        phoneNumber_txt.setText("");
        district_txt.setText("");
        pw_1.setText("");
        pw_2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //through the connection to sds database, add info to sds.accounts
       
               
            
         
        String fName;
        String lName;
        String day_value;
        String month_value;
        String year_value;
        String DOB;
        String email;
        String password;
        String phoneNumber;
        String city_value;
        String district;
   
        Boolean isApproved;

        if (fname_txt.getText().equalsIgnoreCase("") || lname_txt.getText().equalsIgnoreCase("")
                || email_txt.getText().equalsIgnoreCase("") || phoneNumber_txt.getText().equalsIgnoreCase("")
                || district_txt.getText().equalsIgnoreCase("") || pw_1.getText().equalsIgnoreCase("") || pw_2.getText().equalsIgnoreCase("")
                || ((!rad_p.isSelected() && !rad_b.isSelected())) || city.getSelectedIndex() == 0 || day.getSelectedIndex() == 0
                || month.getSelectedIndex() == 0 || year.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Make sure you have filled all required fields.", "Entry Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Arrays.equals(pw_1.getPassword(), pw_2.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Password fields do not match, please try again.", "OOPS", JOptionPane.ERROR_MESSAGE);
        } else {
            fName = fname_txt.getText();
            lName = lname_txt.getText();
            day_value = day.getSelectedItem().toString();
            month_value = month.getSelectedItem().toString();
            year_value = year.getSelectedItem().toString();
            DOB = day_value + "/" + month_value + "/" + year_value;
            email = email_txt.getText();
              ExceptionChecker.isValidEmail(email);
            password = pw_1.getPassword().toString();
            ExceptionChecker.isValidPassword( password);
            phoneNumber = phoneNumber_txt.getText();
            city_value = city.getSelectedItem().toString();
            district = district_txt.getText();
            isApproved = false;
           
 connectionClass.getConnection();
            String qry = "insert into ACCOUNTS_INFO (FIRSTNAME ,LASTNAME ,CITY,DISTRICT,DATEOFBIRTH ,PASSWORD,EMAIL , ADMIN_ID ,ISAPPROVED , TYPE_ACCOUNT ,PHONENUMBER)values(  '" + fName + "', '" + lName + "', '" + city_value + "', '" + district + "','" + DOB + "','" + password + "', '" + email + "', '" + admin + "',  false ,'"+ type+"','" + phoneNumber + "'  )";
            
                
              int stat_1=  connectionClass.getResrultsetupdate(qry);
if ( stat_1>0){
                JOptionPane.showMessageDialog(null, "Account created succesfully, please sign in to begin your journey!", "Success!", JOptionPane.OK_OPTION);
}
                setVisible(false);
                LoginPage_1 LoginPage_1 = new LoginPage_1();
                LoginPage_1.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void rad_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_bActionPerformed
        // TODO add your handling code here:
             if (rad_p.isSelected()) {
                 type="benefiter";}
    }//GEN-LAST:event_rad_bActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCarriedOutOrders_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_2().setVisible(true);
             
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> city;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField district_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel name_txt;
    private javax.swing.JTextField phoneNumber_txt;
    private javax.swing.JPasswordField pw_1;
    private javax.swing.JPasswordField pw_2;
    private javax.swing.JRadioButton rad_b;
    private javax.swing.JRadioButton rad_p;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
