/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superdeliverysystem;

//import az.Register_2;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aseer
 */
public class VehicleRegisteration_41 extends javax.swing.JFrame {

    /**
     * Creates new form vehicleRegisteration
     */
    int id;

    public VehicleRegisteration_41() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lnum = new javax.swing.JTextField();
        plate = new javax.swing.JTextField();
        Make = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        small = new javax.swing.JRadioButton();
        Large = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("License Number ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 160, 140, 15);

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("License Expire Date");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 200, 160, 15);

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Plate Number");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 240, 130, 15);

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Make");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 280, 90, 15);
        jPanel2.add(lnum);
        lnum.setBounds(350, 160, 140, 20);

        plate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateActionPerformed(evt);
            }
        });
        jPanel2.add(plate);
        plate.setBounds(350, 240, 140, 20);
        jPanel2.add(Make);
        Make.setBounds(350, 280, 140, 20);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Car Size");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 320, 70, 15);

        buttonGroup1.add(small);
        small.setText("Small");
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });
        jPanel2.add(small);
        small.setBounds(310, 320, 110, 23);

        buttonGroup1.add(Large);
        Large.setText("Large");
        jPanel2.add(Large);
        Large.setBounds(440, 320, 130, 23);

        jButton2.setText("Register Vehicle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(250, 370, 150, 23);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 370, 71, 23);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(day);
        day.setBounds(350, 200, 40, 20);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(month);
        month.setBounds(390, 200, 50, 20);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        jPanel2.add(year);
        year.setBounds(440, 200, 49, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        Register_2 Register_2 = new Register_2();
        Register_2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String size = "not specified", query;
        int result;
        String date;
        String d, m, y;

        if (small.isSelected()) {
            size = "Small";
        } else if (Large.isSelected()) {
            size = "Large";
        }

        if (lnum.getText().equalsIgnoreCase("") || Make.getText().equalsIgnoreCase("") || plate.getText().equalsIgnoreCase("") || !(small.isSelected() || Large.isSelected())) {
            JOptionPane.showMessageDialog(null, "Make sure you have filled all required fields.", "Entry Error", JOptionPane.ERROR_MESSAGE);
        } else {

            d = day.getSelectedItem().toString();
            m = month.getSelectedItem().toString();
            y = year.getSelectedItem().toString();

            connectionClass.getConnection();

            date = d + "/" + m + "/" + y;
            query = "insert into vehicle(make, platenumber, size, licensenumber, licenseExpiredate ) values('" + Make.getText() + "' ,'" + plate.getText() + "', '" + size + "', '" + lnum.getText() + "', '" + date + "')";

            result = connectionClass.getResrultsetupdate(query);

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Succesfully Registered", "Success!", JOptionPane.OK_OPTION);
                setVisible(false);
                ProviderHomePage_2 ProviderHomePage_2 = new ProviderHomePage_2();
                ProviderHomePage_2.setVisible(true);
            }

        }
        connectionClass.disconnect();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void plateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Large;
    private javax.swing.JTextField Make;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lnum;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField plate;
    private javax.swing.JRadioButton small;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
